### ISSUE TITLE
EOF error in multiprocessing 

### ISSUE THREAD

**Issue by MoMe36** [ASzot/ppo-pytorch#1]
Hello,

On running the code on other environments such as Pendulum or CartPole, I get the following error: 
```
Process Process-1:
Traceback (most recent call last):
  File "/home/mehdi/miniconda3/envs/ML/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/mehdi/miniconda3/envs/ML/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mehdi/Codes/PPO/ppo-pytorch/multiprocessing_env.py", line 44, in worker
    ob, reward, done, info = env.step(data)
  File "/home/mehdi/miniconda3/envs/ML/lib/python3.6/site-packages/gym/wrappers/time_limit.py", line 31, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/mehdi/miniconda3/envs/ML/lib/python3.6/site-packages/gym/envs/classic_control/pendulum.py", line 37, in step
    u = np.clip(u, -self.max_torque, self.max_torque)[0]
IndexError: invalid index to scalar variable.

Traceback (most recent call last):
  File "train.py", line 171, in <module>
    obs, reward, done, info = envs.step(take_actions)
  File "/home/mehdi/Codes/PPO/ppo-pytorch/multiprocessing_env.py", line 111, in step
    return self.step_wait()
  File "/home/mehdi/Codes/PPO/ppo-pytorch/multiprocessing_env.py", line 229, in step_wait
    obs, rews, news, infos = self.venv.step_wait()
  File "/home/mehdi/Codes/PPO/ppo-pytorch/multiprocessing_env.py", line 178, in step_wait
    results = [remote.recv() for remote in self.remotes]
  File "/home/mehdi/Codes/PPO/ppo-pytorch/multiprocessing_env.py", line 178, in <listcomp>
    results = [remote.recv() for remote in self.remotes]
  File "/home/mehdi/miniconda3/envs/ML/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/mehdi/miniconda3/envs/ML/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/mehdi/miniconda3/envs/ML/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

I can't really figure out why. Do you have an item ? 

Thanks ! (:

**Comment by ASzot** [comment]
Yeah, so I didn't support discrete action spaces so CartPole will not work. But for Pendulum the problem is that the action space was of shape (NUME_ENVS,) when it should have been (NUM_ENVS,1). (I think the extra "padding" dimension was dropped somewhere in there). The fix was to just add another line 
```
if len(take_actions.shape) == 1:
            take_actions = np.expand_dims(take_actions, axis=-1)
```
Before taking an action. I just commited that change.
